#!/bin/bash
#Script to install Apache on EC2 instance
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo "<h1>Welcome to Oz's APACHE server page, created with an AWS EC2 instance</h1>" > /var/www/html/index.html
